### PR TITLE
Fixed remote addr (on Caddy reverse proxy) problem

### LINKED ISSUE #15: How to setup nginx/caddy before librespeed?
Hello, thanks to your great work.

I've setup a caddy before speedtest-rust, but it always gets 127.0.0.1 ip. 
my caddy config is
```
http://s.o0x0o.cn, https://s.o0x0o.cn {
        root * /var/lib/librespeed-rs/assets
        file_server
        request_body {
                max_size 100MB
        }
        reverse_proxy /backend/* 127.0.0.1:18080
        tls {
                key_type p384
        }
}
```
I found `find_remote_ip_addr` always get peer_ip from connection
Is this supposed not to run behind a reverse-proxy?

### PR DESCRIPTION
**Pull request by jonirrings**
please check 

close #15

### CODE REVIEW

**Comment by jonirrings** [comment]
I did not find better way than just adding an `else if`

to lower case all header names, may bring more operations than an `else if` and a `hashmap.get`

do you get any better way?

**Comment by SudoDios** [comment]
Thank you @jonirrings 
There is a better idea.
This problem needs to be solved from the root.
Because problems like this can occur in other cases
This way we will have to write if & else for the rest of our lives 😂.
I created new string type
```rust
#[derive(Eq)]
struct UniCaseString(String);

impl PartialEq for UniCaseString {
    fn eq(&self, other: &Self) -> bool {
        self.0.to_lowercase() == other.0.to_lowercase()
    }
}

impl Hash for UniCaseString {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.to_lowercase().hash(state);
    }
}
```
This is better.
What do you think?
Implement this in the code.
If you have any questions, ask.

**Comment by jonirrings** [comment]
got it
I'm trying

**Comment by jonirrings** [comment]
code updated.
I don't like the `.into()` at `request.rs:L204`
should we avoid that?

File: src/http/request.rs [hunk 1]
```diff
@@ -201,7 +201,7 @@ where
             } else {
                 let mut header_parts = header_line.splitn(2, ':');
                 if let (Some(header_key),Some(header_val)) = (header_parts.next(),header_parts.next()) {
-                    headers_out.insert(header_key.trim().to_string(),header_val.trim().to_string());
+                    headers_out.insert(header_key.trim().to_string().into(),header_val.trim().to_string());
```
Comment (jonirrings) [inline src/http/request.rs:204]: any way to avoid the into?

Comment (SudoDios) [reply src/http/request.rs:204]: Because it's too long?
Remove to_string

Comment (jonirrings) [reply src/http/request.rs:204]: 😂, because I‘d like to modify code as less as possible.
I'm wondering any `implicit coercion`, which may be bad practice.

This code seems feasible for me now,
Do you have any other suggestions?

Comment (SudoDios) [reply src/http/request.rs:204]: 😅
very great 👍.
thank you.
I will be back in just 3 days.
I am on my way to a place where there is no internet.
If you find something yourself, do it and we will apply it

Comment (jonirrings) [reply src/http/request.rs:204]: nice~~
enjoy yourself.

**Comment by SudoDios** [comment]
Hi @jonirrings 
Are you sure it's working correctly?
I just tested the code and no headers were being read from the hashmap.
`Borrow<str>` probably doesn't work properly.

**Comment by jonirrings** [comment]
sorry for late reply, I was moving house last weekend, 😂no internet either.
my fault, forgot to test after a manual refactor
I will test and fix this later in the day.

**Comment by SudoDios** [comment]
Okay 👍 😂

**Comment by SudoDios** [comment]
@jonirrings How are you?

**Comment by jonirrings** [comment]
@SudoDios just fine, busy decorating house these days,😂
I tried somehow, `Borrow<str>` did not make it.
maybe use some `case-insensitve map`?

**Comment by SudoDios** [comment]
We should use this for a custom hashmap

**Comment by jonirrings** [comment]
I prefer https://github.com/philipdaniels/case-insensitive-hashmap , maybe a wrapper won't add up too much size?

**Comment by jonirrings** [comment]
I tried the `case insensitive hashmap` above, it works out as expected, can you test it later?

**librespeed-rs behind caddy, http**
behind_caddy
**librespeed-rs behind caddy, https**
behind_caddy_https
**librespeed-rs direct connect**
direct

It seems Caddy adds a lot of overhead~🤡

**Comment by SudoDios** [comment]
It's fine for now.
But in general, you should avoid extra dependencies.
I'll merge this.

**Comment by jonirrings** [comment]
yeah, I'd like to avoid that too😅 which may introduce vulnerability
however, after searching around, I found I could not write a better one in short,
I will try to find a better solution later.
thanks for you concern.🤝

**Comment by SudoDios** [comment]
Thank you very much 🤝.
